COUNTRIES = (
    ('--', '-------'),
    (u'US', u'United States'),
    (u'CA', u'Canada'),
    ('--', '-------'),
    (u'AF', u'Afghanistan'),
    (u'AX', u'\xc5land Islands'),
    (u'AL', u'Albania'),
    (u'DZ', u'Algeria'),
    (u'AS', u'American Samoa'),
    (u'AD', u'Andorra'),
    (u'AO', u'Angola'),
    (u'AI', u'Anguilla'),
    (u'AQ', u'Antarctica'),
    (u'AG', u'Antigua and Barbuda'),
    (u'AR', u'Argentina'),
    (u'AM', u'Armenia'),
    (u'AW', u'Aruba'),
    (u'AU', u'Australia'),
    (u'AT', u'Austria'),
    (u'AZ', u'Azerbaijan'),
    (u'BS', u'Bahamas'),
    (u'BH', u'Bahrain'),
    (u'BD', u'Bangladesh'),
    (u'BB', u'Barbados'),
    (u'BY', u'Belarus'),
    (u'BE', u'Belgium'),
    (u'BZ', u'Belize'),
    (u'BJ', u'Benin'),
    (u'BM', u'Bermuda'),
    (u'BT', u'Bhutan'),
    (u'BO', u'Bolivia, Plurinational State of'),
    (u'BA', u'Bosnia and Herzegovina'),
    (u'BW', u'Botswana'),
    (u'BV', u'Bouvet Island'),
    (u'BR', u'Brazil'),
    (u'IO', u'British Indian Ocean Territory'),
    (u'BN', u'Brunei Darussalam'),
    (u'BG', u'Bulgaria'),
    (u'BF', u'Burkina Faso'),
    (u'BI', u'Burundi'),
    (u'KH', u'Cambodia'),
    (u'CM', u'Cameroon'),
    (u'CA', u'Canada'),
    (u'CV', u'Cape Verde'),
    (u'KY', u'Cayman Islands'),
    (u'CF', u'Central African Republic'),
    (u'TD', u'Chad'),
    (u'CL', u'Chile'),
    (u'CN', u'China'),
    (u'CX', u'Christmas Island'),
    (u'CC', u'Cocos (Keeling) Islands'),
    (u'CO', u'Colombia'),
    (u'KM', u'Comoros'),
    (u'CG', u'Congo'),
    (u'CD', u'Congo, The Democratic Republic of the'),
    (u'CK', u'Cook Islands'),
    (u'CR', u'Costa Rica'),
    (u'CI', u"C\xf4te D'ivoire"),
    (u'HR', u'Croatia'),
    (u'CU', u'Cuba'),
    (u'CY', u'Cyprus'),
    (u'CZ', u'Czech Republic'),
    (u'DK', u'Denmark'),
    (u'DJ', u'Djibouti'),
    (u'DM', u'Dominica'),
    (u'DO', u'Dominican Republic'),
    (u'EC', u'Ecuador'),
    (u'EG', u'Egypt'),
    (u'SV', u'El Salvador'),
    (u'GQ', u'Equatorial Guinea'),
    (u'ER', u'Eritrea'),
    (u'EE', u'Estonia'),
    (u'ET', u'Ethiopia'),
    (u'FK', u'Falkland Islands (Malvinas)'),
    (u'FO', u'Faroe Islands'),
    (u'FJ', u'Fiji'),
    (u'FI', u'Finland'),
    (u'FR', u'France'),
    (u'GF', u'French Guiana'),
    (u'PF', u'French Polynesia'),
    (u'TF', u'French Southern Territories'),
    (u'GA', u'Gabon'),
    (u'GM', u'Gambia'),
    (u'GE', u'Georgia'),
    (u'DE', u'Germany'),
    (u'GH', u'Ghana'),
    (u'GI', u'Gibraltar'),
    (u'GR', u'Greece'),
    (u'GL', u'Greenland'),
    (u'GD', u'Grenada'),
    (u'GP', u'Guadeloupe'),
    (u'GU', u'Guam'),
    (u'GT', u'Guatemala'),
    (u'GG', u'Guernsey'),
    (u'GN', u'Guinea'),
    (u'GW', u'Guinea-bissau'),
    (u'GY', u'Guyana'),
    (u'HT', u'Haiti'),
    (u'HM', u'Heard Island and McDonald Islands'),
    (u'VA', u'Holy See (Vatican City State)'),
    (u'HN', u'Honduras'),
    (u'HK', u'Hong Kong'),
    (u'HU', u'Hungary'),
    (u'IS', u'Iceland'),
    (u'IN', u'India'),
    (u'ID', u'Indonesia'),
    (u'IR', u'Iran, Islamic Republic of'),
    (u'IQ', u'Iraq'),
    (u'IE', u'Ireland'),
    (u'IM', u'Isle of Man'),
    (u'IL', u'Israel'),
    (u'IT', u'Italy'),
    (u'JM', u'Jamaica'),
    (u'JP', u'Japan'),
    (u'JE', u'Jersey'),
    (u'JO', u'Jordan'),
    (u'KZ', u'Kazakhstan'),
    (u'KE', u'Kenya'),
    (u'KI', u'Kiribati'),
    (u'KP', u"Korea, Democratic People's Republic of"),
    (u'KR', u'Korea, Republic of'),
    (u'KW', u'Kuwait'),
    (u'KG', u'Kyrgyzstan'),
    (u'LA', u"Lao People's Democratic Republic"),
    (u'LV', u'Latvia'),
    (u'LB', u'Lebanon'),
    (u'LS', u'Lesotho'),
    (u'LR', u'Liberia'),
    (u'LY', u'Libyan Arab Jamahiriya'),
    (u'LI', u'Liechtenstein'),
    (u'LT', u'Lithuania'),
    (u'LU', u'Luxembourg'),
    (u'MO', u'Macao'),
    (u'MK', u'Macedonia, The Former Yugoslav Republic of'),
    (u'MG', u'Madagascar'),
    (u'MW', u'Malawi'),
    (u'MY', u'Malaysia'),
    (u'MV', u'Maldives'),
    (u'ML', u'Mali'),
    (u'MT', u'Malta'),
    (u'MH', u'Marshall Islands'),
    (u'MQ', u'Martinique'),
    (u'MR', u'Mauritania'),
    (u'MU', u'Mauritius'),
    (u'YT', u'Mayotte'),
    (u'MX', u'Mexico'),
    (u'FM', u'Micronesia, Federated States of'),
    (u'MD', u'Moldova, Republic of'),
    (u'MC', u'Monaco'),
    (u'MN', u'Mongolia'),
    (u'ME', u'Montenegro'),
    (u'MS', u'Montserrat'),
    (u'MA', u'Morocco'),
    (u'MZ', u'Mozambique'),
    (u'MM', u'Myanmar'),
    (u'NA', u'Namibia'),
    (u'NR', u'Nauru'),
    (u'NP', u'Nepal'),
    (u'NL', u'Netherlands'),
    (u'AN', u'Netherlands Antilles'),
    (u'NC', u'New Caledonia'),
    (u'NZ', u'New Zealand'),
    (u'NI', u'Nicaragua'),
    (u'NE', u'Niger'),
    (u'NG', u'Nigeria'),
    (u'NU', u'Niue'),
    (u'NF', u'Norfolk Island'),
    (u'MP', u'Northern Mariana Islands'),
    (u'NO', u'Norway'),
    (u'OM', u'Oman'),
    (u'PK', u'Pakistan'),
    (u'PW', u'Palau'),
    (u'PS', u'Palestinian Territory, Occupied'),
    (u'PA', u'Panama'),
    (u'PG', u'Papua New Guinea'),
    (u'PY', u'Paraguay'),
    (u'PE', u'Peru'),
    (u'PH', u'Philippines'),
    (u'PN', u'Pitcairn'),
    (u'PL', u'Poland'),
    (u'PT', u'Portugal'),
    (u'PR', u'Puerto Rico'),
    (u'QA', u'Qatar'),
    (u'RE', u'R\xe9union'),
    (u'RO', u'Romania'),
    (u'RU', u'Russian Federation'),
    (u'RW', u'Rwanda'),
    (u'BL', u'Saint Barth\xe9lemy'),
    (u'SH', u'Saint Helena, Ascension and Tristan Da Cunha'),
    (u'KN', u'Saint Kitts and Nevis'),
    (u'LC', u'Saint Lucia'),
    (u'MF', u'Saint Martin'),
    (u'PM', u'Saint Pierre and Miquelon'),
    (u'VC', u'Saint Vincent and the Grenadines'),
    (u'WS', u'Samoa'),
    (u'SM', u'San Marino'),
    (u'ST', u'Sao Tome and Principe'),
    (u'SA', u'Saudi Arabia'),
    (u'SN', u'Senegal'),
    (u'RS', u'Serbia'),
    (u'SC', u'Seychelles'),
    (u'SL', u'Sierra Leone'),
    (u'SG', u'Singapore'),
    (u'SK', u'Slovakia'),
    (u'SI', u'Slovenia'),
    (u'SB', u'Solomon Islands'),
    (u'SO', u'Somalia'),
    (u'ZA', u'South Africa'),
    (u'GS', u'South Georgia and the South Sandwich Islands'),
    (u'ES', u'Spain'),
    (u'LK', u'Sri Lanka'),
    (u'SD', u'Sudan'),
    (u'SR', u'Suriname'),
    (u'SJ', u'Svalbard and Jan Mayen'),
    (u'SZ', u'Swaziland'),
    (u'SE', u'Sweden'),
    (u'CH', u'Switzerland'),
    (u'SY', u'Syrian Arab Republic'),
    (u'TW', u'Taiwan, Province of China'),
    (u'TJ', u'Tajikistan'),
    (u'TZ', u'Tanzania, United Republic of'),
    (u'TH', u'Thailand'),
    (u'TL', u'Timor-leste'),
    (u'TG', u'Togo'),
    (u'TK', u'Tokelau'),
    (u'TO', u'Tonga'),
    (u'TT', u'Trinidad and Tobago'),
    (u'TN', u'Tunisia'),
    (u'TR', u'Turkey'),
    (u'TM', u'Turkmenistan'),
    (u'TC', u'Turks and Caicos Islands'),
    (u'TV', u'Tuvalu'),
    (u'UG', u'Uganda'),
    (u'UA', u'Ukraine'),
    (u'AE', u'United Arab Emirates'),
    (u'GB', u'United Kingdom'),
    (u'US', u'United States'),
    (u'UM', u'United States Minor Outlying Islands'),
    (u'UY', u'Uruguay'),
    (u'UZ', u'Uzbekistan'),
    (u'VU', u'Vanuatu'),
    (u'VE', u'Venezuela, Bolivarian Republic of'),
    (u'VN', u'Viet Nam'),
    (u'VG', u'Virgin Islands, British'),
    (u'VI', u'Virgin Islands, U.S.'),
    (u'WF', u'Wallis and Futuna'),
    (u'EH', u'Western Sahara'),
    (u'YE', u'Yemen'),
    (u'ZM', u'Zambia'),
    (u'ZW', u'Zimbabwe'),
)

COUNTRIES_DICT = {
    u'AD': u'Andorra',
    u'AE': u'United Arab Emirates',
    u'AF': u'Afghanistan',
    u'AG': u'Antigua and Barbuda',
    u'AI': u'Anguilla',
    u'AL': u'Albania',
    u'AM': u'Armenia',
    u'AN': u'Netherlands Antilles',
    u'AO': u'Angola',
    u'AQ': u'Antarctica',
    u'AR': u'Argentina',
    u'AS': u'American Samoa',
    u'AT': u'Austria',
    u'AU': u'Australia',
    u'AW': u'Aruba',
    u'AX': u'\xc5land Islands',
    u'AZ': u'Azerbaijan',
    u'BA': u'Bosnia and Herzegovina',
    u'BB': u'Barbados',
    u'BD': u'Bangladesh',
    u'BE': u'Belgium',
    u'BF': u'Burkina Faso',
    u'BG': u'Bulgaria',
    u'BH': u'Bahrain',
    u'BI': u'Burundi',
    u'BJ': u'Benin',
    u'BL': u'Saint Barth\xe9lemy',
    u'BM': u'Bermuda',
    u'BN': u'Brunei Darussalam',
    u'BO': u'Bolivia, Plurinational State of',
    u'BR': u'Brazil',
    u'BS': u'Bahamas',
    u'BT': u'Bhutan',
    u'BV': u'Bouvet Island',
    u'BW': u'Botswana',
    u'BY': u'Belarus',
    u'BZ': u'Belize',
    u'CA': u'Canada',
    u'CC': u'Cocos (Keeling) Islands',
    u'CD': u'Congo, The Democratic Republic of the',
    u'CF': u'Central African Republic',
    u'CG': u'Congo',
    u'CH': u'Switzerland',
    u'CI': u"C\xf4te D'ivoire",
    u'CK': u'Cook Islands',
    u'CL': u'Chile',
    u'CM': u'Cameroon',
    u'CN': u'China',
    u'CO': u'Colombia',
    u'CR': u'Costa Rica',
    u'CU': u'Cuba',
    u'CV': u'Cape Verde',
    u'CX': u'Christmas Island',
    u'CY': u'Cyprus',
    u'CZ': u'Czech Republic',
    u'DE': u'Germany',
    u'DJ': u'Djibouti',
    u'DK': u'Denmark',
    u'DM': u'Dominica',
    u'DO': u'Dominican Republic',
    u'DZ': u'Algeria',
    u'EC': u'Ecuador',
    u'EE': u'Estonia',
    u'EG': u'Egypt',
    u'EH': u'Western Sahara',
    u'ER': u'Eritrea',
    u'ES': u'Spain',
    u'ET': u'Ethiopia',
    u'FI': u'Finland',
    u'FJ': u'Fiji',
    u'FK': u'Falkland Islands (Malvinas)',
    u'FM': u'Micronesia, Federated States of',
    u'FO': u'Faroe Islands',
    u'FR': u'France',
    u'GA': u'Gabon',
    u'GB': u'United Kingdom',
    u'GD': u'Grenada',
    u'GE': u'Georgia',
    u'GF': u'French Guiana',
    u'GG': u'Guernsey',
    u'GH': u'Ghana',
    u'GI': u'Gibraltar',
    u'GL': u'Greenland',
    u'GM': u'Gambia',
    u'GN': u'Guinea',
    u'GP': u'Guadeloupe',
    u'GQ': u'Equatorial Guinea',
    u'GR': u'Greece',
    u'GS': u'South Georgia and the South Sandwich Islands',
    u'GT': u'Guatemala',
    u'GU': u'Guam',
    u'GW': u'Guinea-bissau',
    u'GY': u'Guyana',
    u'HK': u'Hong Kong',
    u'HM': u'Heard Island and McDonald Islands',
    u'HN': u'Honduras',
    u'HR': u'Croatia',
    u'HT': u'Haiti',
    u'HU': u'Hungary',
    u'ID': u'Indonesia',
    u'IE': u'Ireland',
    u'IL': u'Israel',
    u'IM': u'Isle of Man',
    u'IN': u'India',
    u'IO': u'British Indian Ocean Territory',
    u'IQ': u'Iraq',
    u'IR': u'Iran, Islamic Republic of',
    u'IS': u'Iceland',
    u'IT': u'Italy',
    u'JE': u'Jersey',
    u'JM': u'Jamaica',
    u'JO': u'Jordan',
    u'JP': u'Japan',
    u'KE': u'Kenya',
    u'KG': u'Kyrgyzstan',
    u'KH': u'Cambodia',
    u'KI': u'Kiribati',
    u'KM': u'Comoros',
    u'KN': u'Saint Kitts and Nevis',
    u'KP': u"Korea, Democratic People's Republic of", 'KW': 'Kuwait',
    u'KR': u'Korea, Republic of',
    u'KY': u'Cayman Islands',
    u'KZ': u'Kazakhstan',
    u'LA': u"Lao People's Democratic Republic", 'TV': 'Tuvalu',
    u'LB': u'Lebanon',
    u'LC': u'Saint Lucia',
    u'LI': u'Liechtenstein',
    u'LK': u'Sri Lanka',
    u'LR': u'Liberia',
    u'LS': u'Lesotho',
    u'LT': u'Lithuania',
    u'LU': u'Luxembourg',
    u'LV': u'Latvia',
    u'LY': u'Libyan Arab Jamahiriya',
    u'MA': u'Morocco',
    u'MC': u'Monaco',
    u'MD': u'Moldova, Republic of',
    u'ME': u'Montenegro',
    u'MF': u'Saint Martin',
    u'MG': u'Madagascar',
    u'MH': u'Marshall Islands',
    u'MK': u'Macedonia, The Former Yugoslav Republic of',
    u'ML': u'Mali',
    u'MM': u'Myanmar',
    u'MN': u'Mongolia',
    u'MO': u'Macao',
    u'MP': u'Northern Mariana Islands',
    u'MQ': u'Martinique',
    u'MR': u'Mauritania',
    u'MS': u'Montserrat',
    u'MT': u'Malta',
    u'MU': u'Mauritius',
    u'MV': u'Maldives',
    u'MW': u'Malawi',
    u'MX': u'Mexico',
    u'MY': u'Malaysia',
    u'MZ': u'Mozambique',
    u'NA': u'Namibia',
    u'NC': u'New Caledonia',
    u'NE': u'Niger',
    u'NF': u'Norfolk Island',
    u'NG': u'Nigeria',
    u'NI': u'Nicaragua',
    u'NL': u'Netherlands',
    u'NO': u'Norway',
    u'NP': u'Nepal',
    u'NR': u'Nauru',
    u'NU': u'Niue',
    u'NZ': u'New Zealand',
    u'OM': u'Oman',
    u'PA': u'Panama',
    u'PE': u'Peru',
    u'PF': u'French Polynesia',
    u'PG': u'Papua New Guinea',
    u'PH': u'Philippines',
    u'PK': u'Pakistan',
    u'PL': u'Poland',
    u'PM': u'Saint Pierre and Miquelon',
    u'PN': u'Pitcairn',
    u'PR': u'Puerto Rico',
    u'PS': u'Palestinian Territory, Occupied',
    u'PT': u'Portugal',
    u'PW': u'Palau',
    u'PY': u'Paraguay',
    u'QA': u'Qatar',
    u'RE': u'R\xe9union',
    u'RO': u'Romania',
    u'RS': u'Serbia',
    u'RU': u'Russian Federation',
    u'RW': u'Rwanda',
    u'SA': u'Saudi Arabia',
    u'SB': u'Solomon Islands',
    u'SC': u'Seychelles',
    u'SD': u'Sudan',
    u'SE': u'Sweden',
    u'SG': u'Singapore',
    u'SH': u'Saint Helena, Ascension and Tristan Da Cunha',
    u'SI': u'Slovenia',
    u'SJ': u'Svalbard and Jan Mayen',
    u'SK': u'Slovakia',
    u'SL': u'Sierra Leone',
    u'SM': u'San Marino',
    u'SN': u'Senegal',
    u'SO': u'Somalia',
    u'SR': u'Suriname',
    u'ST': u'Sao Tome and Principe',
    u'SV': u'El Salvador',
    u'SY': u'Syrian Arab Republic',
    u'SZ': u'Swaziland',
    u'TC': u'Turks and Caicos Islands',
    u'TD': u'Chad',
    u'TF': u'French Southern Territories',
    u'TG': u'Togo',
    u'TH': u'Thailand',
    u'TJ': u'Tajikistan',
    u'TK': u'Tokelau',
    u'TL': u'Timor-leste',
    u'TM': u'Turkmenistan',
    u'TN': u'Tunisia',
    u'TO': u'Tonga',
    u'TR': u'Turkey',
    u'TT': u'Trinidad and Tobago',
    u'TW': u'Taiwan, Province of China',
    u'TZ': u'Tanzania, United Republic of',
    u'UA': u'Ukraine',
    u'UG': u'Uganda',
    u'UM': u'United States Minor Outlying Islands',
    u'US': u'United States',
    u'UY': u'Uruguay',
    u'UZ': u'Uzbekistan',
    u'VA': u'Holy See (Vatican City State)',
    u'VC': u'Saint Vincent and the Grenadines',
    u'VE': u'Venezuela, Bolivarian Republic of',
    u'VG': u'Virgin Islands, British',
    u'VI': u'Virgin Islands, U.S.',
    u'VN': u'Viet Nam',
    u'VU': u'Vanuatu',
    u'WF': u'Wallis and Futuna',
    u'WS': u'Samoa',
    u'YE': u'Yemen',
    u'YT': u'Mayotte',
    u'ZA': u'South Africa',
    u'ZM': u'Zambia',
    u'ZW': u'Zimbabwe',
}
