'''
INDUSTRIES = (
    ('01', 'Accounting'),
    ('02', 'Aerospace and Defense'),
    ('03', 'Auto and Trucks'),
    ('04', 'Beverages'),
    ('05', 'Biotechnology and Pharmaceutical Products'),
    ('06', 'Business Services'),
    ('07', 'Business Supplies'),
    ('08', 'Chemicals'),
    ('09', 'Coal'),
    ('10', 'Computer Hardware'),
    ('11', 'Computer Software'),
    ('12', 'Construction and Building Materials'),
    ('13', 'Consumer Goods'),
    ('14', 'Diversified Manufacturing'),
    ('15', 'Electrical Equipment'),
    ('16', 'Electronic Equipment'),
    ('17', 'Entertainment'),
    ('18', 'Environmental Control'),
    ('19', 'Food Products'),
    ('20', 'Healthcare'),
    ('21', 'Home Builders'),
    ('22', 'Law'),
    ('23', 'Machinery'),
    ('24', 'Measuring and Control Equipment'),
    ('25', 'Medical Equipment'),
    ('26', 'Mining and Metals'),
    ('27', 'Oil and Gas'),
    ('28', 'Oil and Gas Services'),
    ('29', 'Packaging and Containers'),
    ('30', 'Paper and Pulp'),
    ('31', 'Personal Services'),
    ('32', 'Printing and Publishing'),
    ('33', 'Recreation'),
    ('34', 'Restaurants and Hotels/Motels'),
    ('35', 'Retail'),
    ('36', 'Steel Works'),
    ('37', 'Telecommunications'),
    ('38', 'Tobacco'),
    ('39', 'Transportation'),
    ('40', 'Utilities'),
    ('41', 'Wholesale'),
)

INDUSTRIES_DICT = {
    '01': 'Accounting',
    '02': 'Aerospace and Defense',
    '03': 'Auto and Trucks',
    '04': 'Beverages',
    '05': 'Biotechnology and Pharmaceutical Products',
    '06': 'Business Services',
    '07': 'Business Supplies',
    '08': 'Chemicals',
    '09': 'Coal',
    '10': 'Computer Hardware',
    '11': 'Computer Software',
    '12': 'Construction and Building Materials',
    '13': 'Consumer Goods',
    '14': 'Diversified Manufacturing',
    '15': 'Electrical Equipment',
    '16': 'Electronic Equipment',
    '17': 'Entertainment',
    '18': 'Environmental Control',
    '19': 'Food Products',
    '20': 'Healthcare',  
    '21': 'Home Builders',
    '22': 'Law',
    '23': 'Machinery',
    '24': 'Measuring and Control Equipment',
    '25': 'Medical Equipment',
    '26': 'Mining and Metals',
    '27': 'Oil and Gas',
    '28': 'Oil and Gas Services',   
    '29': 'Packaging and Containers',
    '30': 'Paper and Pulp',  
    '31': 'Personal Services',
    '32': 'Printing and Publishing',
    '33': 'Recreation',
    '34': 'Restaurants and Hotels/Motels',
    '35': 'Retail',
    '36': 'Steel Works',
    '37': 'Telecommunications',
    '38': 'Tobacco',
    '39': 'Transportation',
    '40': 'Utilities',
    '41': 'Wholesale',
}
'''

INDUSTRIES = (
    ('--', '-------'),
    ('01', 'Agriculture'),
    ('02', 'Arts'),
    ('03', 'Construction'),
    ('04', 'Consumer Goods'),
    ('05', 'Corporate Services'),
    ('06', 'Education'),
    ('07', 'Entertainment'),
    ('08', 'Finance'),
    ('09', 'Government'),
    ('10', 'Legal'),
    ('11', 'Manufacturing'),
    ('12', 'Media'),
    ('13', 'Medical and Health Care'),
    ('14', 'Non-Profit'),
    ('15', 'Recreation'),
    ('16', 'Scientific'),
    ('17', 'Service Industry'),
    ('18', 'Technology'),
    ('19', 'Transportation'),
    ('20', 'Travel'),
)

INDUSTRIES_DICT = {
    '--': '-------',
    '01': 'Agriculture',
    '02': 'Arts',
    '03': 'Construction',
    '04': 'Consumer Goods',
    '05': 'Corporate Services',
    '06': 'Education',
    '07': 'Entertainment',
    '08': 'Finance',
    '09': 'Government',
    '10': 'Legal',
    '11': 'Manufacturing',
    '12': 'Media',
    '13': 'Medical and Health Care',
    '14': 'Non-Profit',
    '15': 'Recreation',
    '16': 'Scientific',
    '17': 'Service Industry',
    '18': 'Technology',
    '19': 'Transportation',
    '20': 'Travel',
}
