STATE_PROVINCE = (
    ('--', '-------'),
    (u'AB', u'Alberta'),
    (u'AK', u'Alaska'),
    (u'AL', u'Alabama'),
    (u'AR', u'Arkansas'),
    (u'AS', u'American Samoa'),
    (u'AZ', u'Arizona'),
    (u'BC', u'British Columbia'),
    (u'CA', u'California'),
    (u'CO', u'Colorado'),
    (u'CT', u'Connecticut'),
    (u'DC', u'District of Columbia'),
    (u'DE', u'Delaware'),
    (u'FL', u'Florida'),
    (u'GA', u'Georgia'),
    (u'GU', u'Guam'),
    (u'HI', u'Hawaii'),
    (u'IA', u'Iowa'),
    (u'ID', u'Idaho'),
    (u'IL', u'Illinois'),
    (u'IN', u'Indiana'),
    (u'KS', u'Kansas'),
    (u'KY', u'Kentucky'),
    (u'LA', u'Louisiana'),
    (u'MA', u'Massachusetts'),
    (u'MB', u'Manitoba'),
    (u'MD', u'Maryland'),
    (u'ME', u'Maine'),
    (u'MI', u'Michigan'),
    (u'MN', u'Minnesota'),
    (u'MO', u'Missouri'),
    (u'MP', u'Northern Mariana Islands'),
    (u'MS', u'Mississippi'),
    (u'MT', u'Montana'),
    (u'NB', u'New Brunswick'),
    (u'NC', u'North Carolina'),
    (u'ND', u'North Dakota'),
    (u'NE', u'Nebraska'),
    (u'NF', u'Newfoundland and Labrador'),
    (u'NH', u'New Hampshire'),
    (u'NJ', u'New Jersey'),
    (u'NM', u'New Mexico'),
    (u'NS', u'Nova Scotia'),
    (u'NT', u'Northwest Territories'),
    (u'NU', u'Nunavut'),
    (u'NV', u'Nevada'),
    (u'NY', u'New York'),
    (u'OH', u'Ohio'),
    (u'OK', u'Oklahoma'),
    (u'ON', u'Ontario'),
    (u'OR', u'Oregon'),
    (u'PA', u'Pennsylvania'),
    (u'PE', u'Prince Edward Island'),
    (u'PR', u'Puerto Rico'),
    (u'QC', u'Quebec'),
    (u'RI', u'Rhode Island'),
    (u'SC', u'South Carolina'),
    (u'SD', u'South Dakota'),
    (u'SK', u'Saskatchewan'),
    (u'TN', u'Tennessee'),
    (u'TX', u'Texas'),
    (u'UT', u'Utah'),
    (u'VA', u'Virginia'),
    (u'VI', u'Virgin Islands'),
    (u'VT', u'Vermont'),
    (u'WA', u'Washington'),
    (u'WI', u'Wisconsin'),
    (u'WV', u'West Virginia'),
    (u'WY', u'Wyoming'),
    (u'YK', u'Yukon'),
)

STATE_PROVINCE_DICT = {
   u'AB': u'Alberta',
   u'AK': u'Alaska',
   u'AL': u'Alabama',
   u'AR': u'Arkansas',
   u'AS': u'American Samoa',
   u'AZ': u'Arizona',
   u'BC': u'British Columbia',
   u'CA': u'California',
   u'CO': u'Colorado',
   u'CT': u'Connecticut',
   u'DC': u'District of Columbia',
   u'DE': u'Delaware',
   u'FL': u'Florida',
   u'GA': u'Georgia',
   u'GU': u'Guam',
   u'HI': u'Hawaii',
   u'IA': u'Iowa',
   u'ID': u'Idaho',
   u'IL': u'Illinois',
   u'IN': u'Indiana',
   u'KS': u'Kansas',
   u'KY': u'Kentucky',
   u'LA': u'Louisiana',
   u'MA': u'Massachusetts',
   u'MB': u'Manitoba',
   u'MD': u'Maryland',
   u'ME': u'Maine',
   u'MI': u'Michigan',
   u'MN': u'Minnesota',
   u'MO': u'Missouri',
   u'MP': u'Northern Mariana Islands',
   u'MS': u'Mississippi',
   u'MT': u'Montana',
   u'NB': u'New Brunswick',
   u'NC': u'North Carolina',
   u'ND': u'North Dakota',
   u'NE': u'Nebraska',
   u'NF': u'Newfoundland and Labrador',
   u'NH': u'New Hampshire',
   u'NJ': u'New Jersey',
   u'NM': u'New Mexico',
   u'NS': u'Nova Scotia',
   u'NT': u'Northwest Territories',
   u'NU': u'Nunavut',
   u'NV': u'Nevada',
   u'NY': u'New York',
   u'OH': u'Ohio',
   u'OK': u'Oklahoma',
   u'ON': u'Ontario',
   u'OR': u'Oregon',
   u'PA': u'Pennsylvania',
   u'PE': u'Prince Edward Island',
   u'PR': u'Puerto Rico',
   u'QC': u'Quebec',
   u'RI': u'Rhode Island',
   u'SC': u'South Carolina',
   u'SD': u'South Dakota',
   u'SK': u'Saskatchewan',
   u'TN': u'Tennessee',
   u'TX': u'Texas',
   u'UT': u'Utah',
   u'VA': u'Virginia',
   u'VI': u'Virgin Islands',
   u'VT': u'Vermont',
   u'WA': u'Washington',
   u'WI': u'Wisconsin',
   u'WV': u'West Virginia',
   u'WY': u'Wyoming',
   u'YK': u'Yukon',
}

